<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 Sumatra Revision.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/Sumatra Revision-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Sumbar.geometry} material={gltf.nodes.Sumbar.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Medan.geometry} material={gltf.nodes.Medan.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Aceh.geometry} material={gltf.nodes.Aceh.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Riau.geometry} material={gltf.nodes.Riau.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Kepri.geometry} material={gltf.nodes.Kepri.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Jambi.geometry} material={gltf.nodes.Jambi.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Bengkulu.geometry} material={gltf.nodes.Bengkulu.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Babel.geometry} material={gltf.nodes.Babel.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Sumsel.geometry} material={gltf.nodes.Sumsel.material} scale={22.28} />
    <T.Mesh geometry={gltf.nodes.Lampung.geometry} material={gltf.nodes.Lampung.material} scale={22.28} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
