<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 sumatra.glb --transform
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { interactivity } from '@threlte/extras';
	import { spring, tweened, type Spring } from 'svelte/motion';

	interactivity();

	export const ref = new Group();

	const gltf = useGltf('/sumatra-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	let provinces = [
		{ name: 'Aceh', h: 10 },
		{ name: 'Sumut', h: 10 },
		{ name: 'Sumbar', h: 10 },
		{ name: 'Bengkulu', h: 10 },
		{ name: 'Riau', h: 10 },
		{ name: 'Jambi', h: 10 },
		{ name: 'Lampung', h: 10 },
		{ name: 'Sumsel', h: 10 },
		{ name: 'Babel', h: 10 },
		{ name: 'Kepri', h: 10 }
	];

	const hoverProvince = (index: number) => {
		const temp = [...provinces];
		temp[index].h = 30;
		provinces = temp;
		console.log(index);
	};

	const leaveProvince = (index: number) => {
		const temp = [...provinces];
		temp[index].h = 10;
		provinces = temp;
		console.log(index);
	};
</script>

<T.PerspectiveCamera
	makeDefault
	position={[20, 40, 30]}
	on:create={({ ref }) => {
		ref.lookAt(20, 10, 20);
	}}
/>

<T.DirectionalLight position={[0, 10, 10]} />

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		{#each provinces as province, index}
			<T.Mesh
				on:pointerenter={() => {
					hoverProvince(index);
				}}
				on:pointerleave={() => {
					leaveProvince(index);
				}}
				geometry={gltf.nodes[`${province.name}`].geometry}
				scale={39.23}
				scale.y={province.h}
			>
				<T.MeshStandardMaterial color="hotpink" />
			</T.Mesh>
		{/each}

		<!-- <T.Mesh
			geometry={gltf.nodes.Aceh.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Sumut.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Sumbar.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Bengkulu.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Riau.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Jambi.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Lampung.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Sumsel.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Babel.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/>
		<T.Mesh
			geometry={gltf.nodes.Kepri.geometry}
			material={gltf.materials['SVGMat.078']}
			scale={39.23}
		/> -->
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
